language: c
compiler:
  - gcc
  - clang
os:
  - linux

branches:
  only:
    - master
    - coverity
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "D2imBRzCuqhwU0SZiejdn7nh2TpYfcFfYNpta8KsQihbJ6v8qw8Um5oHP+KnksPGUGa4uDRCElUUxLq6ixEMwhCNazjXC1MnHhah+EQCkcmXN9bxpxHSRfyU/ydTqHn+hiNl19CgSPDwMankPR6GdP/2BgX+C5RkZaIt7MLkH3HQhQiXSXiboxzPRivPHrxtirojhvVHQpXaX0NB//rMpsuQ52SdJjNJ/9yT6L9fg3BVq6VhJ83nsY3LUQSWG5+rjhwTI2jXoSJUR7c9k+0eLaIsnJlNYeklgZwsiWmknEKWNFcgX9tOVTboHjkl0OasRyo+Ijow73Acnf55wDr7rvPqiGmipDZ/YjQNHIOF7vki6JQhEqrP4JVV3LPkqCok7LjOYb65/0zFmVU+pJOJVd8ZR09QxtC47VAlOqkyjL8yJimZey3oL7CKp6VuguCwm0ADjjiNR0Iph7jjhV5GoP4oMrbS2Z1hN9yzPSX3OHVAumnIzCrpDtI42mz9G0RjKSDXwTgpPn7FuNfwTy9DKwVB7vGWcU8XlEaJ0vLxGX+jz1eOCCMtDK3HyPGRFqmfzxaRzs3bDEyp91IbAi02Zk6TxfxDQKeH/OhmGDhM72aaRblk3yOtdUw/ApF6YNIRmfQefAID7Znf3SSRSmGwHnW+f9N63LpSL5Ms0w3E6Xc="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-c++
      - autoconf
      - pkg-config
      - make
      - automake
      - libxml2-devel
      - libxml2
  coverity_scan:
    project:
      name: "CESNET/Nemea-Supervisor"
      description: "Nemea Supervisor - management and monitoring Nemea module"
    notification_email: cejkat@cesnet.cz
    build_command_prepend: "./bootstrap.sh && ./configure -q && make clean"
    build_command:   "make"
    branch_pattern: coverity

before_install:
   - ( git clone https://github.com/CESNET/nemea-framework; cd nemea-framework; ./bootstrap.sh && ./configure -q --prefix=/usr && make -j10 && sudo make install; )

script:
  - ./bootstrap.sh && ./configure --disable-repobuild && make check

