name: C/C++ CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc g++ autoconf pkg-config make automake libxml2-dev libxml2
        ( git clone https://github.com/CESNET/Nemea-Framework; cd Nemea-Framework; ./bootstrap.sh && ./configure -q --prefix=/usr && make -j10 && sudo make install; )
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: configure with debug
      run: ./configure --enable-debug CXXFLAGS=-coverage CFLAGS=-coverage LDFLAGS=-lgcov
    - name: rebuild and check
      run: make clean; make check
    - uses: codecov/codecov-action@v1
      with:
        flags: tests # optional
        name: nemea-supervisor # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

